name: Linter-Build

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    LinterBuild:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: install packages
              run: npm i

            - name: start linter
              run: npm run all

            - name: start build
              run: npm run build
